version: '3.8'
services:
  authentication_database:
    image: mongo:4.4
    container_name: authentication_database
    ports:
      - 27018:27017
    volumes:
      - ./volumes/authentication_database/:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${AUTHENTICATION_DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${AUTHENTICATION_DATABASE_PASSWORD}
  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    container_name: authentication
    ports:
      - 3000:3000
    restart: always
