version: '3.8'
services:
  # 📦 Message brokers.
  message_broker:
    image: rabbitmq:3-management-alpine
    container_name: message_broker
    volumes:
      - ./volumes/message_broker/data/:/var/lib/rabbitmq/
      - ./volumes/message_broker/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    logging:
      driver: none
  # 💽 Repositories.
  authentication_database:
    image: mongo:4.4
    container_name: authentication_database
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${AUTHENTICATION_DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${AUTHENTICATION_DATABASE_PASSWORD}
    restart: always
    logging:
      driver: none
  ask_database:
    image: mongo:4.4
    container_name: ask_database
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ASK_DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${ASK_DATABASE_PASSWORD}
    restart: always
    logging:
      driver: none
  # 🔧 Services.
  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    container_name: authentication
    ports:
      - 3000:3000
    restart: on-failure:10
  ask:
    build:
      context: ./ask
      dockerfile: Dockerfile
    container_name: ask
    ports:
      - 3001:3001
    restart: on-failure:10
  daily-ask:
    build:
      context: ./daily-ask
      dockerfile: Dockerfile
    container_name: daily-ask
    restart: on-failure:10
