export type SocialNetworkDomainErrorCodes =
  | 'INVALID_SOCIAL_NETWORK_NAME_LENGTH'
  | 'INVALID_SOCIAL_NETWORK_URL_LENGTH'
  | 'SOCIAL_NETWORK_CREATE_FAILED'
  | 'SOCIAL_NETWORK_DELETE_FAILED'
  | 'SOCIAL_NETWORK_NOT_FOUND'
  | 'SOCIAL_NETWORK_UPDATE_FAILED';
