export type AvatarDomainErrorCodes =
  | 'AVATAR_CREATE_FAILED'
  | 'AVATAR_DELETE_FAILED'
  | 'AVATAR_REPLACE_FAILED'
  | 'INVALID_AVATAR_FILE_MIME_TYPE'
  | 'INVALID_AVATAR_FILE_SIZE'
  | 'NO_AVATAR_STORED_YET';
