export type ServiceError = {
  code: ServiceErrorCode;
  message: string;
};

export type ServiceErrorCode =
| SchedulerServiceErrorCode
| ScraperServiceErrorCode;

export type SchedulerServiceErrorCode =
| 'SCHEDULER_SERVICE_CALLBACK_FAILED'
| 'SCHEDULER_SERVICE_UNEXPECTED'
| 'SCHEDULER_SERVICE_INVALID_PATTERN';

export type ScraperServiceErrorCode =
| 'SCRAPER_SERVICE_EMPTY_CONTENT'
| 'SCRAPER_SERVICE_FAILED_TO_CLOSE'
| 'SCRAPER_SERVICE_FAILED_TO_CONNECT'
| 'SCRAPER_SERVICE_FAILED_TO_SCRAPE'
| 'SCRAPER_SERVICE_MISSING_CONNECTION'
| 'SCRAPER_SERVICE_SELECTOR_NOT_FOUND'
| 'SCRAPER_SERVICE_UNEXPECTED_STATUS_CODE'
| 'SCRAPER_SERVICE_UNREACHABLE_PAGE';
