export type UserDomainErrorCodes =
  | 'INVALID_CREDENTIALS'
  | 'INVALID_EMAIL'
  | 'INVALID_EMAIL_LENGTH'
  | 'INVALID_NAME'
  | 'INVALID_NAME_LENGTH'
  | 'INVALID_PASSWORD_LENGTH'
  | 'INVALID_USERNAME'
  | 'INVALID_USERNAME_LENGTH'
  | 'NO_USER_CREATED_YET'
  | 'SINGLE_USER_ONLY'
  | 'USER_PERMISSION_DENIED'
  | 'USER_UPDATE_FAILED';
