export type MessageBrokerError = {
  code: MessageBrokerErrorCode;
  message: string;
};

export type MessageBrokerErrorCode =
| 'MESSAGE_BROKER_CHANNEL_IS_CLOSED_ERROR'
| 'MESSAGE_BROKER_FAILED_TO_CLOSE_ERROR'
| 'MESSAGE_BROKER_FAILED_TO_CONNECT_ERROR'
| 'MESSAGE_BROKER_FAILED_TO_CONSUME_MESSAGE_ERROR'
| 'MESSAGE_BROKER_FAILED_TO_SEND_MESSAGE_ERROR'
| 'MESSAGE_BROKER_NO_MESSAGE_AVAILABLE_ERROR'
| 'MESSAGE_BROKER_ON_MESSAGE_NOT_IMPLEMENTED_ERROR';
