export type ControllerError = {
  code: ControllerErrorCode;
  message: string;
  statusCode: number;
};

export type ControllerErrorCode =
| UserControllerErrorCode
| CommonControllerErrorCode
| ProfileControllerErrorCode
| TokenServiceControllerErrorCode;

export type UserControllerErrorCode =
| 'INVALID_USER_USERNAME_LENGTH_CONTROLLER_ERROR'
| 'SINGLE_USER_ONLY_CONTROLLER_ERROR'
| 'USER_CREATION_FAILED_CONTROLLER_ERROR'
| 'USER_NOT_FOUND_CONTROLLER_ERROR'
| 'USER_UPDATE_FAILED_CONTROLLER_ERROR'
| 'USERNAME_ALREADY_EXISTS_CONTROLLER_ERROR';

export type CommonControllerErrorCode =
| 'INTERNAL_SERVER_CONTROLLER_ERROR'
| 'PERMISSION_DENIED_CONTROLLER_ERROR';

export type ProfileControllerErrorCode =
| 'INVALID_PROFILE_INTEREST_LENGTH_CONTROLLER_ERROR'
| 'INVALID_PROFILE_POSITION_LENGTH_CONTROLLER_ERROR'
| 'INVALID_PROFILE_QUOTE_LENGTH_CONTROLLER_ERROR'
| 'PROFILE_CREATION_FAILED_CONTROLLER_ERROR'
| 'PROFILE_NOT_FOUND_CONTROLLER_ERROR'
| 'PROFILE_UPDATE_FAILED_CONTROLLER_ERROR'
| 'SINGLE_PROFILE_ONLY_CONTROLLER_ERROR';

export type TokenServiceControllerErrorCode =
| 'TOKEN_SERVICE_INVALID_TOKEN_CONTROLLER_ERROR'
| 'TOKEN_SERVICE_EXPIRED_TOKEN_CONTROLLER_ERROR';
