export type BrokerError = {
  code: BrokerErrorCode;
  message: string;
};

export type BrokerErrorCode =
| 'BROKER_CHANNEL_IS_CLOSED'
| 'BROKER_FAILED_TO_ACK'
| 'BROKER_FAILED_TO_CONNECT'
| 'BROKER_FAILED_TO_CONSUME_MESSAGE'
| 'BROKER_FAILED_TO_PROCESS_MESSAGE'
| 'BROKER_FAILED_TO_SEND_MESSAGE'
| 'BROKER_NO_MESSAGE_AVAILABLE'
| 'BROKER_ON_MESSAGE_NOT_IMPLEMENTED';
