export type MessageBrokerError = {
  code: MessageBrokerErrorCode;
  message: string;
};

export type MessageBrokerErrorCode =
| 'MESSAGE_BROKER_CHANNEL_IS_CLOSED'
| 'MESSAGE_BROKER_FAILED_TO_CLOSE'
| 'MESSAGE_BROKER_FAILED_TO_CONNECT'
| 'MESSAGE_BROKER_FAILED_TO_CONSUME_MESSAGE'
| 'MESSAGE_BROKER_FAILED_TO_PROCESS_MESSAGE'
| 'MESSAGE_BROKER_FAILED_TO_SEND_MESSAGE'
| 'MESSAGE_BROKER_NO_MESSAGE_AVAILABLE'
| 'MESSAGE_BROKER_ON_MESSAGE_NOT_IMPLEMENTED';
